global:
  scrape_interval: 5s  # how often to collect metrics

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3002']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
